version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  go_app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on: 
      - postgres # This service depends on redis. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    environment:
      PG_HOST: postgres
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      
volumes:
  postgres_data:

networks:
  backend: